### ISSUE TITLE
What does this do exactly?

### ISSUE THREAD

**Issue by tenkuu** [alexbft/chiitrans#1]
![2014-03-17_20-10-34](https://f.cloud.github.com/assets/2627419/2444141/f322bc72-ae4a-11e3-8c61-1a21a5d9c866.png)

**Comment by alexbft** [comment]
@DoodleChan good question.

This option determines what to do when a new context appears. Contexts(threads) are text streams captured from the VN.

**Read all new contexts** - all new contexts will be selected for translation.
**Ignore new contexts** - no new contexts will be selected.
**Switch to new contexts** - when new context appear, it becomes selected and all the other contexts are deselected.
**Smart filtering** - an "intelligent guess" approach, used by default. It works like "read all new contexts" until any non-standard context appears. Non-standard contexts are custom hooks predefined in the engine and generally are the best choice. So, from that moment, only non-standard contexts would be selected.
