### ISSUE TITLE
Keyboard layout settings

### ISSUE THREAD

**Issue by rjjj** [alexbft/chiitrans#2]
The capture windows GUI text hotkey set to tilde ~ occupies the apostrophe ' spot on English (United Kingdom) and English (Ireland) keyboard settings, meaning that you have to close the program to type it.

A minor annoyance and not a big problem, just something I'd noticed since switching from chiitrans2.

**Comment by alexbft** [comment]
Why do you have to close anything to type an apostrophe, I wonder?

> Keyboard layout settings

No, I'm not going to make it configurable. But I can change the tilde hotkey to something else, do you have any suggestions?

**Comment by rjjj** [comment]
presumably it's a scancode difference between UK and US keyboard layout and for this reason it's taking ' as the global hotkey instead of typing an apostrophe

can't think of a perfect replacement for it, although maybe one of the F-keys would work

**Comment by alexbft** [comment]
Ah. I got it. So when you try to type an apostrophe, it triggers the ChiitransLite hotkey instead.

**Comment by rjjj** [comment]
yep, that's my understanding of it

**Comment by alexbft** [comment]
I've changed the hotkey to CTRL+~
