### ISSUE TITLE
ChiiTrans Lite not showing any threads or performing normal dettaching behavior. (Windows 10)

### ISSUE THREAD

**Issue by JustAQuinn** [alexbft/chiitrans#8]
I use .NET Framework 4.7 since I'm on Windows 10 with the Creator's Update. I say this because everyone on VN forums keeps saying don't update or else ChiiTrans won't work anymore.

ChiiTrans Lite hasn't been working recently and I'm not sure why. Whenever I hook a game, no threads ever show up. Nothing hangs or stalls. Then when I close the game, ChiiTrans doesn't do anything, as if the game is still running. I tried seven VNs from all kinds of developers, a RPG Maker VX, and a RPG Maker VX Ace game. Same problem.

If it helps, ITHVNR was able to hook a game ChiiTrans could not.

**Comment by alexbft** [comment]
Hi, this project is abandonware by now. You can still use it with ITHVNR if you want.

**Comment by JustAQuinn** [comment]
:C I'm sorry to hear that, Chii was my fav tool for the job. I hope someone picks up the torch one day since it's the best attachment GUI besides VNR but doesn't bog down my machine. Best of luck!
